title: 'Folkuniversitetet - Kortkurs: React.js'
description: Kortkurs 20yhp i ramverket React.js
template:
  repo: folkuniversitetet-react-h21-template
  name: folkuniversitetet-react-ht21
  description: Här hittar du alla kodexempel som är namngivna efter dess modul.
before:
  - type: createIssue
    title: Welcome!
    body: module-1-hello-world.md
steps:
  - title: Modul 1 - Hello World
    description: >-
      I denna modul finns information om kursens förkunskaper, upplägg och
      tekniska krav för att komma igång
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: Welcome!
        body: module-2-components.md
  - title: Modul 2 - Komponenter
    description: >-
      I denna modul utreder vi vad ett ramverk är samt hur man tänker i
      komponenter.
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: Welcome!
        body: module-3-interactivity.md
  - title: Modul 3 - Interaktivitet
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: Welcome!
        body: module-4-state.md
  - title: Modul 4 - State
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: Welcome!
        body: module-5-react-router.md
  - title: Modul 5 - React Router
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: Welcome!
        body: module-6-redux.md
  - title: Modul 6 - Redux
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
      - type: createIssue
        title: Welcome!
        body: module-7-final-examination.md
  - title: Modul 7 - Slutexamination
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
